wifi_ssid: "Название вашей Wi-Fi сети"
wifi_password: "Пароль от вашей WiFi сети"

mqtt_broker: "Ваш IP адрес брокера, например 192.168.1.11"
mqtt_port: 1883
mqtt_username: "Ваш username"
mqtt_password: "Ваш пароль"
